export const initialFieldWorkers = [
  {
    "id": "fw-1",
    "name": "John Deng",
    "role": "Field Worker",
    "email": "john.deng@adra.org",
    "phone": "+211-921-550101",
    "supervisor_id": "sup-1",
    "supervisor_name": "Emmanuel Adeyemi",
    "programme_id": "prg1",
    "programme": "Emergency Food Security & Livelihoods Resilience",
    "state": "Eastern Equatoria",
    "county": "Kapoeta South",
    "payam": "Kapoeta Town",
    "boma": "Machi",
    "assigned_area": "Eastern Equatoria (Kapoeta South / Kapoeta Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 21,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 21,
    "reports_returned": 1,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-2",
    "name": "Mary James",
    "role": "Field Worker",
    "email": "mary.james@adra.org",
    "phone": "+211-921-550102",
    "supervisor_id": "sup-1",
    "supervisor_name": "Emmanuel Adeyemi",
    "programme_id": "prg2",
    "programme": "Emergency Food Security & Livelihoods Resilience",
    "state": "Eastern Equatoria",
    "county": "Kapoeta South",
    "payam": "Longeleya",
    "boma": "Hai Malakal South",
    "assigned_area": "Eastern Equatoria (Kapoeta South / Longeleya)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 24,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 24,
    "reports_returned": 2,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-3",
    "name": "Amina Abdi",
    "role": "Field Worker",
    "email": "field.worker@adra.org",
    "phone": "+211-920-000005",
    "supervisor_id": "sup-1",
    "supervisor_name": "Emmanuel Adeyemi",
    "programme_id": "prg3",
    "programme": "Community Mobilization & Relief",
    "state": "Eastern Equatoria",
    "county": "Kapoeta South",
    "payam": "Kapoeta Town",
    "boma": "Longeleya",
    "assigned_area": "Eastern Equatoria (Kapoeta South / Kapoeta Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 27,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 27,
    "reports_returned": 0,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-4",
    "name": "Peter Lado",
    "role": "Field Worker",
    "email": "peter.lado@adra.org",
    "phone": "+211-921-550104",
    "supervisor_id": "sup-1",
    "supervisor_name": "Emmanuel Adeyemi",
    "programme_id": "prg4",
    "programme": "Sustainable WASH & Clean Water Infrastructure",
    "state": "Eastern Equatoria",
    "county": "Torit",
    "payam": "Torit Town",
    "boma": "Hai Iluhum",
    "assigned_area": "Eastern Equatoria (Torit / Torit Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 30,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 30,
    "reports_returned": 1,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-5",
    "name": "Grace Keji",
    "role": "Field Worker",
    "email": "grace.keji@adra.org",
    "phone": "+211-921-550105",
    "supervisor_id": "sup-1",
    "supervisor_name": "Emmanuel Adeyemi",
    "programme_id": "prg5",
    "programme": "Maternal, Infant & Child Health and Nutrition",
    "state": "Eastern Equatoria",
    "county": "Magwi",
    "payam": "Magwi Central",
    "boma": "Magwi Town",
    "assigned_area": "Eastern Equatoria (Magwi / Magwi Central)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 33,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 33,
    "reports_returned": 2,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-6",
    "name": "Simon Kiden",
    "role": "Field Worker",
    "email": "simon.kiden@adra.org",
    "phone": "+211-922-550201",
    "supervisor_id": "sup-2",
    "supervisor_name": "Mary Akech",
    "programme_id": "prg1",
    "programme": "Emergency Food Security & Livelihoods Resilience",
    "state": "Central Equatoria",
    "county": "Juba",
    "payam": "Juba Na Bari",
    "boma": "Tongping",
    "assigned_area": "Central Equatoria (Juba / Juba Na Bari)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 36,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 36,
    "reports_returned": 0,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-7",
    "name": "Rose Poni",
    "role": "Field Worker",
    "email": "rose.poni@adra.org",
    "phone": "+211-922-550202",
    "supervisor_id": "sup-2",
    "supervisor_name": "Mary Akech",
    "programme_id": "prg2",
    "programme": "Sustainable WASH & Clean Water Infrastructure",
    "state": "Central Equatoria",
    "county": "Juba",
    "payam": "Munuki",
    "boma": "Block B",
    "assigned_area": "Central Equatoria (Juba / Munuki)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 39,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 39,
    "reports_returned": 1,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-8",
    "name": "Luka Wani",
    "role": "Field Worker",
    "email": "luka.wani@adra.org",
    "phone": "+211-922-550203",
    "supervisor_id": "sup-2",
    "supervisor_name": "Mary Akech",
    "programme_id": "prg3",
    "programme": "Youth Livelihoods & Vocational Empowerment",
    "state": "Central Equatoria",
    "county": "Yei",
    "payam": "Yei Town",
    "boma": "Lomuku",
    "assigned_area": "Central Equatoria (Yei / Yei Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 42,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 42,
    "reports_returned": 2,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-9",
    "name": "Agnes Dawa",
    "role": "Field Worker",
    "email": "agnes.dawa@adra.org",
    "phone": "+211-922-550204",
    "supervisor_id": "sup-2",
    "supervisor_name": "Mary Akech",
    "programme_id": "prg4",
    "programme": "Maternal, Infant & Child Health and Nutrition",
    "state": "Central Equatoria",
    "county": "Kajo-Keji",
    "payam": "Kangapo I",
    "boma": "Wudu",
    "assigned_area": "Central Equatoria (Kajo-Keji / Kangapo I)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 20,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 20,
    "reports_returned": 0,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-10",
    "name": "Jacob Taban",
    "role": "Field Worker",
    "email": "jacob.taban@adra.org",
    "phone": "+211-922-550205",
    "supervisor_id": "sup-2",
    "supervisor_name": "Mary Akech",
    "programme_id": "prg5",
    "programme": "Rapid Emergency Disaster Response",
    "state": "Central Equatoria",
    "county": "Terekeka",
    "payam": "Terekeka Center",
    "boma": "Terekeka Town",
    "assigned_area": "Central Equatoria (Terekeka / Terekeka Center)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 23,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 23,
    "reports_returned": 1,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-11",
    "name": "Deng Majok",
    "role": "Field Worker",
    "email": "deng.majok@adra.org",
    "phone": "+211-923-550301",
    "supervisor_id": "sup-3",
    "supervisor_name": "David Deng",
    "programme_id": "prg1",
    "programme": "Rapid Emergency Disaster Response & Shelter Recovery",
    "state": "Jonglei",
    "county": "Bor",
    "payam": "Baidit",
    "boma": "Kolnyang",
    "assigned_area": "Jonglei (Bor / Baidit)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 26,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 26,
    "reports_returned": 2,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-12",
    "name": "Nyibol Kuol",
    "role": "Field Worker",
    "email": "nyibol.kuol@adra.org",
    "phone": "+211-923-550302",
    "supervisor_id": "sup-3",
    "supervisor_name": "David Deng",
    "programme_id": "prg2",
    "programme": "Sustainable WASH & Flood Mitigation",
    "state": "Jonglei",
    "county": "Bor",
    "payam": "Anyidi",
    "boma": "Makol Chuei",
    "assigned_area": "Jonglei (Bor / Anyidi)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 29,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 29,
    "reports_returned": 0,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-13",
    "name": "Garang Akech",
    "role": "Field Worker",
    "email": "garang.akech@adra.org",
    "phone": "+211-923-550303",
    "supervisor_id": "sup-3",
    "supervisor_name": "David Deng",
    "programme_id": "prg3",
    "programme": "Emergency Food Security & Rations",
    "state": "Jonglei",
    "county": "Twic East",
    "payam": "Panyagor",
    "boma": "Panyagor Center",
    "assigned_area": "Jonglei (Twic East / Panyagor)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 32,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 32,
    "reports_returned": 1,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-14",
    "name": "Mary Yar",
    "role": "Field Worker",
    "email": "mary.yar@adra.org",
    "phone": "+211-923-550304",
    "supervisor_id": "sup-3",
    "supervisor_name": "David Deng",
    "programme_id": "prg4",
    "programme": "Maternal, Infant & Child Health and Nutrition",
    "state": "Jonglei",
    "county": "Akobo",
    "payam": "Akobo Town",
    "boma": "Akobo Center",
    "assigned_area": "Jonglei (Akobo / Akobo Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 35,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 35,
    "reports_returned": 2,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-15",
    "name": "Peter Thon",
    "role": "Field Worker",
    "email": "peter.thon@adra.org",
    "phone": "+211-923-550305",
    "supervisor_id": "sup-3",
    "supervisor_name": "David Deng",
    "programme_id": "prg5",
    "programme": "Emergency Relief & Relocations",
    "state": "Jonglei",
    "county": "Duk",
    "payam": "Duk Padiet",
    "boma": "Padiet Town",
    "assigned_area": "Jonglei (Duk / Duk Padiet)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 38,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 38,
    "reports_returned": 0,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-16",
    "name": "Mabor Manyiel",
    "role": "Field Worker",
    "email": "mabor.manyiel@adra.org",
    "phone": "+211-924-550401",
    "supervisor_id": "sup-4",
    "supervisor_name": "Santino Bol",
    "programme_id": "prg1",
    "programme": "Emergency Food Security & Seed Distribution",
    "state": "Lakes",
    "county": "Rumbek Centre",
    "payam": "Matangai",
    "boma": "Aduel",
    "assigned_area": "Lakes (Rumbek Centre / Matangai)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 41,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 41,
    "reports_returned": 1,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-17",
    "name": "Ayen Marial",
    "role": "Field Worker",
    "email": "ayen.marial@adra.org",
    "phone": "+211-924-550402",
    "supervisor_id": "sup-4",
    "supervisor_name": "Santino Bol",
    "programme_id": "prg2",
    "programme": "Maternal, Infant & Child Health and Nutrition",
    "state": "Lakes",
    "county": "Rumbek Centre",
    "payam": "Rumbek Town",
    "boma": "Meen",
    "assigned_area": "Lakes (Rumbek Centre / Rumbek Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 19,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 19,
    "reports_returned": 2,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-18",
    "name": "Daniel Dut",
    "role": "Field Worker",
    "email": "daniel.dut@adra.org",
    "phone": "+211-924-550403",
    "supervisor_id": "sup-4",
    "supervisor_name": "Santino Bol",
    "programme_id": "prg3",
    "programme": "Sustainable WASH & Clean Water Infrastructure",
    "state": "Lakes",
    "county": "Yirol West",
    "payam": "Yirol Town",
    "boma": "Yirol Center",
    "assigned_area": "Lakes (Yirol West / Yirol Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 22,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 22,
    "reports_returned": 0,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-19",
    "name": "Achol Malek",
    "role": "Field Worker",
    "email": "achol.malek@adra.org",
    "phone": "+211-924-550404",
    "supervisor_id": "sup-4",
    "supervisor_name": "Santino Bol",
    "programme_id": "prg4",
    "programme": "Youth Livelihoods & Vocational Empowerment",
    "state": "Lakes",
    "county": "Cueibet",
    "payam": "Cueibet Center",
    "boma": "Cueibet Town",
    "assigned_area": "Lakes (Cueibet / Cueibet Center)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 25,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 25,
    "reports_returned": 1,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-20",
    "name": "Maker Chol",
    "role": "Field Worker",
    "email": "maker.chol@adra.org",
    "phone": "+211-924-550405",
    "supervisor_id": "sup-4",
    "supervisor_name": "Santino Bol",
    "programme_id": "prg5",
    "programme": "Rapid Emergency Disaster Response",
    "state": "Lakes",
    "county": "Awerial",
    "payam": "Mingkaman",
    "boma": "Mingkaman Hub",
    "assigned_area": "Lakes (Awerial / Mingkaman)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 28,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 28,
    "reports_returned": 2,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-21",
    "name": "Akol Deng",
    "role": "Field Worker",
    "email": "akol.deng@adra.org",
    "phone": "+211-925-550501",
    "supervisor_id": "sup-5",
    "supervisor_name": "Garang Deng Akol",
    "programme_id": "prg1",
    "programme": "Emergency Food Security & Livelihoods Resilience",
    "state": "Northern Bahr el Ghazal",
    "county": "Aweil Centre",
    "payam": "Aweil Town",
    "boma": "Maper",
    "assigned_area": "Northern Bahr el Ghazal (Aweil Centre / Aweil Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 31,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 31,
    "reports_returned": 0,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-22",
    "name": "Abuk Garang",
    "role": "Field Worker",
    "email": "abuk.garang@adra.org",
    "phone": "+211-925-550502",
    "supervisor_id": "sup-5",
    "supervisor_name": "Garang Deng Akol",
    "programme_id": "prg2",
    "programme": "Maternal, Infant & Child Health and Nutrition",
    "state": "Northern Bahr el Ghazal",
    "county": "Aweil East",
    "payam": "Wanyjok",
    "boma": "Wanyjok Center",
    "assigned_area": "Northern Bahr el Ghazal (Aweil East / Wanyjok)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 34,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 34,
    "reports_returned": 1,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-23",
    "name": "Lual Mawien",
    "role": "Field Worker",
    "email": "lual.mawien@adra.org",
    "phone": "+211-925-550503",
    "supervisor_id": "sup-5",
    "supervisor_name": "Garang Deng Akol",
    "programme_id": "prg3",
    "programme": "Sustainable WASH & Clean Water Infrastructure",
    "state": "Northern Bahr el Ghazal",
    "county": "Aweil West",
    "payam": "Nyamlell",
    "boma": "Nyamlell Town",
    "assigned_area": "Northern Bahr el Ghazal (Aweil West / Nyamlell)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 37,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 37,
    "reports_returned": 2,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-24",
    "name": "Achan Tong",
    "role": "Field Worker",
    "email": "achan.tong@adra.org",
    "phone": "+211-925-550504",
    "supervisor_id": "sup-5",
    "supervisor_name": "Garang Deng Akol",
    "programme_id": "prg4",
    "programme": "Youth Livelihoods & Agronomy",
    "state": "Northern Bahr el Ghazal",
    "county": "Aweil North",
    "payam": "Gok Machar",
    "boma": "Gok Center",
    "assigned_area": "Northern Bahr el Ghazal (Aweil North / Gok Machar)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 40,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 40,
    "reports_returned": 0,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-25",
    "name": "Dut Kuany",
    "role": "Field Worker",
    "email": "dut.kuany@adra.org",
    "phone": "+211-925-550505",
    "supervisor_id": "sup-5",
    "supervisor_name": "Garang Deng Akol",
    "programme_id": "prg5",
    "programme": "Emergency Dispatch & Relief",
    "state": "Northern Bahr el Ghazal",
    "county": "Aweil South",
    "payam": "Malek Aleu",
    "boma": "Malek Center",
    "assigned_area": "Northern Bahr el Ghazal (Aweil South / Malek Aleu)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 18,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 18,
    "reports_returned": 1,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-26",
    "name": "Gatluak Riek",
    "role": "Field Worker",
    "email": "gatluak.riek@adra.org",
    "phone": "+211-926-550601",
    "supervisor_id": "sup-6",
    "supervisor_name": "Nyaluak Gatluak",
    "programme_id": "prg1",
    "programme": "Rapid Emergency Disaster Response & Shelter Recovery",
    "state": "Unity",
    "county": "Rubkona",
    "payam": "Bentiu Town",
    "boma": "Sector 2",
    "assigned_area": "Unity (Rubkona / Bentiu Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 21,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 21,
    "reports_returned": 2,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-27",
    "name": "Nyakume Ruon",
    "role": "Field Worker",
    "email": "nyakume.ruon@adra.org",
    "phone": "+211-926-550602",
    "supervisor_id": "sup-6",
    "supervisor_name": "Nyaluak Gatluak",
    "programme_id": "prg2",
    "programme": "Sustainable WASH & Clean Water Infrastructure",
    "state": "Unity",
    "county": "Rubkona",
    "payam": "Rubkona Port",
    "boma": "Port Zone",
    "assigned_area": "Unity (Rubkona / Rubkona Port)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 24,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 24,
    "reports_returned": 0,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-28",
    "name": "James Gatkek",
    "role": "Field Worker",
    "email": "james.gatkek@adra.org",
    "phone": "+211-926-550603",
    "supervisor_id": "sup-6",
    "supervisor_name": "Nyaluak Gatluak",
    "programme_id": "prg3",
    "programme": "Emergency Food Security & Rations",
    "state": "Unity",
    "county": "Leer",
    "payam": "Leer Town",
    "boma": "Leer Center",
    "assigned_area": "Unity (Leer / Leer Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 27,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 27,
    "reports_returned": 1,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-29",
    "name": "Nyaduoth Chuol",
    "role": "Field Worker",
    "email": "nyaduoth.chuol@adra.org",
    "phone": "+211-926-550604",
    "supervisor_id": "sup-6",
    "supervisor_name": "Nyaluak Gatluak",
    "programme_id": "prg4",
    "programme": "Maternal, Infant & Child Health and Nutrition",
    "state": "Unity",
    "county": "Mayom",
    "payam": "Mayom Center",
    "boma": "Mayom Town",
    "assigned_area": "Unity (Mayom / Mayom Center)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 30,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 30,
    "reports_returned": 2,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-30",
    "name": "Peter Dak",
    "role": "Field Worker",
    "email": "peter.dak@adra.org",
    "phone": "+211-926-550605",
    "supervisor_id": "sup-6",
    "supervisor_name": "Nyaluak Gatluak",
    "programme_id": "prg5",
    "programme": "IDP Community Outreach & Verification",
    "state": "Unity",
    "county": "Koch",
    "payam": "Koch Town",
    "boma": "Koch Center",
    "assigned_area": "Unity (Koch / Koch Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 33,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 33,
    "reports_returned": 0,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-31",
    "name": "Oluak Ajak",
    "role": "Field Worker",
    "email": "oluak.ajak@adra.org",
    "phone": "+211-927-550701",
    "supervisor_id": "sup-7",
    "supervisor_name": "Amina Hassan",
    "programme_id": "prg1",
    "programme": "Maternal, Infant & Child Health and Nutrition",
    "state": "Upper Nile",
    "county": "Malakal",
    "payam": "Malakal Central",
    "boma": "Sector 3",
    "assigned_area": "Upper Nile (Malakal / Malakal Central)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 36,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 36,
    "reports_returned": 1,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-32",
    "name": "Nyadeng Othow",
    "role": "Field Worker",
    "email": "nyadeng.othow@adra.org",
    "phone": "+211-927-550702",
    "supervisor_id": "sup-7",
    "supervisor_name": "Amina Hassan",
    "programme_id": "prg2",
    "programme": "Sustainable WASH & Clean Water Infrastructure",
    "state": "Upper Nile",
    "county": "Malakal",
    "payam": "Malakal Town",
    "boma": "POC Zone",
    "assigned_area": "Upper Nile (Malakal / Malakal Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 39,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 39,
    "reports_returned": 2,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-33",
    "name": "Yousif Deng",
    "role": "Field Worker",
    "email": "yousif.deng@adra.org",
    "phone": "+211-927-550703",
    "supervisor_id": "sup-7",
    "supervisor_name": "Amina Hassan",
    "programme_id": "prg3",
    "programme": "Cross-Border Food Security & Logistics",
    "state": "Upper Nile",
    "county": "Renk",
    "payam": "Renk Central",
    "boma": "Renk North",
    "assigned_area": "Upper Nile (Renk / Renk Central)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 42,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 42,
    "reports_returned": 0,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-34",
    "name": "Martha Nyikang",
    "role": "Field Worker",
    "email": "martha.nyikang@adra.org",
    "phone": "+211-927-550704",
    "supervisor_id": "sup-7",
    "supervisor_name": "Amina Hassan",
    "programme_id": "prg4",
    "programme": "Refugee Emergency Assistance",
    "state": "Upper Nile",
    "county": "Maban",
    "payam": "Bunj",
    "boma": "Bunj Center",
    "assigned_area": "Upper Nile (Maban / Bunj)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 20,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 20,
    "reports_returned": 1,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-35",
    "name": "David Kur",
    "role": "Field Worker",
    "email": "david.kur@adra.org",
    "phone": "+211-927-550705",
    "supervisor_id": "sup-7",
    "supervisor_name": "Amina Hassan",
    "programme_id": "prg5",
    "programme": "Rapid Emergency Disaster Response",
    "state": "Upper Nile",
    "county": "Melut",
    "payam": "Melut Town",
    "boma": "Melut Center",
    "assigned_area": "Upper Nile (Melut / Melut Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 23,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 23,
    "reports_returned": 2,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-36",
    "name": "Madut Anei",
    "role": "Field Worker",
    "email": "madut.anei@adra.org",
    "phone": "+211-928-550801",
    "supervisor_id": "sup-8",
    "supervisor_name": "Achol Malual",
    "programme_id": "prg1",
    "programme": "Emergency Food Security & Livelihoods Resilience",
    "state": "Warrap",
    "county": "Gogrial West",
    "payam": "Kuajok Town",
    "boma": "Alek",
    "assigned_area": "Warrap (Gogrial West / Kuajok Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 26,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 26,
    "reports_returned": 0,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-37",
    "name": "Aker Deng",
    "role": "Field Worker",
    "email": "aker.deng@adra.org",
    "phone": "+211-928-550802",
    "supervisor_id": "sup-8",
    "supervisor_name": "Achol Malual",
    "programme_id": "prg2",
    "programme": "Maternal, Infant & Child Health and Nutrition",
    "state": "Warrap",
    "county": "Gogrial West",
    "payam": "Kuajok Central",
    "boma": "Kuajok Zone 1",
    "assigned_area": "Warrap (Gogrial West / Kuajok Central)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 29,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 29,
    "reports_returned": 1,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-38",
    "name": "Wol Bol",
    "role": "Field Worker",
    "email": "wol.bol@adra.org",
    "phone": "+211-928-550803",
    "supervisor_id": "sup-8",
    "supervisor_name": "Achol Malual",
    "programme_id": "prg3",
    "programme": "Sustainable WASH & Borehole Rehabilitation",
    "state": "Warrap",
    "county": "Tonj South",
    "payam": "Tonj Town",
    "boma": "Tonj Center",
    "assigned_area": "Warrap (Tonj South / Tonj Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 32,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 32,
    "reports_returned": 2,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-39",
    "name": "Aruai Ring",
    "role": "Field Worker",
    "email": "aruai.ring@adra.org",
    "phone": "+211-928-550804",
    "supervisor_id": "sup-8",
    "supervisor_name": "Achol Malual",
    "programme_id": "prg4",
    "programme": "Disaster Shelter Recovery & NFI",
    "state": "Warrap",
    "county": "Twic",
    "payam": "Turalei",
    "boma": "Turalei Hub",
    "assigned_area": "Warrap (Twic / Turalei)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 35,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 35,
    "reports_returned": 0,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-40",
    "name": "Santino Mayen",
    "role": "Field Worker",
    "email": "santino.mayen@adra.org",
    "phone": "+211-928-550805",
    "supervisor_id": "sup-8",
    "supervisor_name": "Achol Malual",
    "programme_id": "prg5",
    "programme": "Youth Livelihoods & Vocational Training",
    "state": "Warrap",
    "county": "Tonj North",
    "payam": "Warrap Town",
    "boma": "Warrap Center",
    "assigned_area": "Warrap (Tonj North / Warrap Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 38,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 38,
    "reports_returned": 1,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-41",
    "name": "Francis Hassan",
    "role": "Field Worker",
    "email": "francis.hassan@adra.org",
    "phone": "+211-929-550901",
    "supervisor_id": "sup-9",
    "supervisor_name": "Michael Loba",
    "programme_id": "prg1",
    "programme": "Sustainable WASH & Clean Water Infrastructure",
    "state": "Western Bahr el Ghazal",
    "county": "Wau",
    "payam": "Wau North",
    "boma": "Hai Kosti",
    "assigned_area": "Western Bahr el Ghazal (Wau / Wau North)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 41,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 41,
    "reports_returned": 2,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-42",
    "name": "Juliana Paul",
    "role": "Field Worker",
    "email": "juliana.paul@adra.org",
    "phone": "+211-929-550902",
    "supervisor_id": "sup-9",
    "supervisor_name": "Michael Loba",
    "programme_id": "prg2",
    "programme": "Emergency Food Security & Livelihoods",
    "state": "Western Bahr el Ghazal",
    "county": "Wau",
    "payam": "Wau South",
    "boma": "Bazia",
    "assigned_area": "Western Bahr el Ghazal (Wau / Wau South)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 19,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 19,
    "reports_returned": 0,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-43",
    "name": "Joseph Faki",
    "role": "Field Worker",
    "email": "joseph.faki@adra.org",
    "phone": "+211-929-550903",
    "supervisor_id": "sup-9",
    "supervisor_name": "Michael Loba",
    "programme_id": "prg3",
    "programme": "Community Agriculture & Livelihoods",
    "state": "Western Bahr el Ghazal",
    "county": "Raja",
    "payam": "Raja Town",
    "boma": "Raja Center",
    "assigned_area": "Western Bahr el Ghazal (Raja / Raja Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 22,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 22,
    "reports_returned": 1,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-44",
    "name": "Clementina Mario",
    "role": "Field Worker",
    "email": "clementina.mario@adra.org",
    "phone": "+211-929-550904",
    "supervisor_id": "sup-9",
    "supervisor_name": "Michael Loba",
    "programme_id": "prg4",
    "programme": "Maternal, Infant & Child Health and Nutrition",
    "state": "Western Bahr el Ghazal",
    "county": "Jur River",
    "payam": "Kangi",
    "boma": "Kangi Town",
    "assigned_area": "Western Bahr el Ghazal (Jur River / Kangi)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 25,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 25,
    "reports_returned": 2,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-45",
    "name": "Gabriel Ukelo",
    "role": "Field Worker",
    "email": "gabriel.ukelo@adra.org",
    "phone": "+211-929-550905",
    "supervisor_id": "sup-9",
    "supervisor_name": "Michael Loba",
    "programme_id": "prg5",
    "programme": "Rapid Emergency Disaster Response",
    "state": "Western Bahr el Ghazal",
    "county": "Wau",
    "payam": "Lokoloko",
    "boma": "Lokoloko Center",
    "assigned_area": "Western Bahr el Ghazal (Wau / Lokoloko)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 28,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 28,
    "reports_returned": 0,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-46",
    "name": "Samuel Zindo",
    "role": "Field Worker",
    "email": "samuel.zindo@adra.org",
    "phone": "+211-930-551001",
    "supervisor_id": "sup-10",
    "supervisor_name": "Grace Samuel Zambia",
    "programme_id": "prg1",
    "programme": "Youth Livelihoods & Vocational Empowerment",
    "state": "Western Equatoria",
    "county": "Yambio",
    "payam": "Yambio Central",
    "boma": "Hai Gabat",
    "assigned_area": "Western Equatoria (Yambio / Yambio Central)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 31,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 31,
    "reports_returned": 1,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-47",
    "name": "Joyce Nande",
    "role": "Field Worker",
    "email": "joyce.nande@adra.org",
    "phone": "+211-930-551002",
    "supervisor_id": "sup-10",
    "supervisor_name": "Grace Samuel Zambia",
    "programme_id": "prg2",
    "programme": "Agro-forestry & Seed Distribution",
    "state": "Western Equatoria",
    "county": "Yambio",
    "payam": "Yambio Town",
    "boma": "Ikpiro",
    "assigned_area": "Western Equatoria (Yambio / Yambio Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 34,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 34,
    "reports_returned": 2,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-48",
    "name": "Victor Bagba",
    "role": "Field Worker",
    "email": "victor.bagba@adra.org",
    "phone": "+211-930-551003",
    "supervisor_id": "sup-10",
    "supervisor_name": "Grace Samuel Zambia",
    "programme_id": "prg3",
    "programme": "Emergency Food Security & Rations",
    "state": "Western Equatoria",
    "county": "Nzara",
    "payam": "Nzara Town",
    "boma": "Nzara Center",
    "assigned_area": "Western Equatoria (Nzara / Nzara Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 37,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 37,
    "reports_returned": 0,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-49",
    "name": "Esther Miidie",
    "role": "Field Worker",
    "email": "esther.miidie@adra.org",
    "phone": "+211-930-551004",
    "supervisor_id": "sup-10",
    "supervisor_name": "Grace Samuel Zambia",
    "programme_id": "prg4",
    "programme": "Sustainable WASH & Nutrition",
    "state": "Western Equatoria",
    "county": "Maridi",
    "payam": "Maridi Town",
    "boma": "Maridi Central",
    "assigned_area": "Western Equatoria (Maridi / Maridi Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 40,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 40,
    "reports_returned": 1,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-50",
    "name": "Moses Gangura",
    "role": "Field Worker",
    "email": "moses.gangura@adra.org",
    "phone": "+211-930-551005",
    "supervisor_id": "sup-10",
    "supervisor_name": "Grace Samuel Zambia",
    "programme_id": "prg5",
    "programme": "Emergency Recovery & Relocation",
    "state": "Western Equatoria",
    "county": "Tambura",
    "payam": "Tambura Town",
    "boma": "Tambura Center",
    "assigned_area": "Western Equatoria (Tambura / Tambura Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 18,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 18,
    "reports_returned": 2,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-51",
    "name": "Konyi Ismael",
    "role": "Field Worker",
    "email": "konyi.ismael@adra.org",
    "phone": "+211-931-551101",
    "supervisor_id": "sup-11",
    "supervisor_name": "Baba Konyi",
    "programme_id": "prg1",
    "programme": "Emergency Food Relief & Nutrition",
    "state": "Administrative Areas",
    "county": "Greater Pibor",
    "payam": "Pibor Town",
    "boma": "Verteth",
    "assigned_area": "Administrative Areas (Greater Pibor / Pibor Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 21,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 21,
    "reports_returned": 0,
    "last_activity": "Active on field route (1h ago)",
    "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-52",
    "name": "Chacha Boman",
    "role": "Field Worker",
    "email": "chacha.boman@adra.org",
    "phone": "+211-931-551102",
    "supervisor_id": "sup-11",
    "supervisor_name": "Baba Konyi",
    "programme_id": "prg2",
    "programme": "Maternal & Child Health",
    "state": "Administrative Areas",
    "county": "Greater Pibor",
    "payam": "Pibor Central",
    "boma": "Manyabol",
    "assigned_area": "Administrative Areas (Greater Pibor / Pibor Central)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 24,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 24,
    "reports_returned": 1,
    "last_activity": "Active on field route (3h ago)",
    "avatar": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-53",
    "name": "Miyen Kuol",
    "role": "Field Worker",
    "email": "miyen.kuol@adra.org",
    "phone": "+211-931-551103",
    "supervisor_id": "sup-11",
    "supervisor_name": "Baba Konyi",
    "programme_id": "prg3",
    "programme": "Rapid Emergency Disaster Response",
    "state": "Administrative Areas",
    "county": "Abyei Area",
    "payam": "Abyei Town",
    "boma": "Agok Hub",
    "assigned_area": "Administrative Areas (Abyei Area / Abyei Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 27,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 27,
    "reports_returned": 2,
    "last_activity": "Active on field route (5h ago)",
    "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-54",
    "name": "Arop Deng",
    "role": "Field Worker",
    "email": "arop.deng@adra.org",
    "phone": "+211-931-551104",
    "supervisor_id": "sup-11",
    "supervisor_name": "Baba Konyi",
    "programme_id": "prg4",
    "programme": "Sustainable WASH & Clean Water Infrastructure",
    "state": "Administrative Areas",
    "county": "Abyei Area",
    "payam": "Alal",
    "boma": "Alal Center",
    "assigned_area": "Administrative Areas (Abyei Area / Alal)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 30,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 30,
    "reports_returned": 0,
    "last_activity": "Active on field route (7h ago)",
    "avatar": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  },
  {
    "id": "fw-55",
    "name": "Monyroor Mijak",
    "role": "Field Worker",
    "email": "monyroor.mijak@adra.org",
    "phone": "+211-931-551105",
    "supervisor_id": "sup-11",
    "supervisor_name": "Baba Konyi",
    "programme_id": "prg5",
    "programme": "Resilience Logistics & Food Security",
    "state": "Administrative Areas",
    "county": "Ruweng",
    "payam": "Pariang Town",
    "boma": "Pariang Center",
    "assigned_area": "Administrative Areas (Ruweng / Pariang Town)",
    "current_status": "Available",
    "active_assignments": 0,
    "completed_assignments": 33,
    "pending_reports": 0,
    "overdue_assessments": 0,
    "reports_submitted": 33,
    "reports_returned": 1,
    "last_activity": "Active on field route (9h ago)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  }
];
